Fix the issue caused by promise.then.finally.
TypeError: test_helper_1.setupEnvs(...).then(...).finally is not a function
It's strange that, local `npm test` desn't show this error.